# Generated by Django 5.1.5 on 2025-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BattleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battle_id", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("opponent_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Battle Log",
                "verbose_name_plural": "Battle Logs",
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("max_wins", models.PositiveIntegerField()),
                ("reward", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
            },
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("badge_id", models.PositiveIntegerField()),
                ("clan_score", models.PositiveIntegerField()),
                ("members_count", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Clan",
                "verbose_name_plural": "Clans",
            },
        ),
        migrations.CreateModel(
            name="ClanWar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("war_id", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("battle_count", models.PositiveIntegerField()),
                ("wins", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Clan War",
                "verbose_name_plural": "Clan Wars",
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("clan_score", models.PositiveIntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Leaderboard",
                "verbose_name_plural": "Leaderboards",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveIntegerField()),
                ("trophies", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
    ]
