# Generated by Django 5.1.5 on 2025-01-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clashroyale", "0002_alter_challenge_end_time_alter_challenge_start_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClanWar",
        ),
    ]
